language: scala

scala:
   - 2.10.4
   - 2.11.6

services:
  - cassandra
  - mongodb
  - elasticsearch

before_install:
  - git clone https://github.com/Stratio/spark-mongodb.git
  - cd spark-mongodb
  - mvn -q install -DskipUTs -DskipITs -DskipTests

before_script:
  - sleep 10

script:

  - mvn test -Dmaven.test.failure=true

after_success:
  - bash <(curl -s https://codecov.io/bash)
